# Site settings
title: JazzCloud
email: in@jazzcloud.co
description: "Backends, APIs, refactoring."
baseurl: ""
url: "http://jazzcloud.co"
twitter_username: jazzcloud
# github_username:  inem

# Build settings
markdown: kramdown
permalink: pretty
